certificates:
  - id: 1
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIGYjCCBUqgAwIBAgIQNbz+XFRPZXvByYCfTf+OZTANBgkqhkiG9w0BAQsFADCB
      jzELMAkGA1UEBhMCR0IxGzAZBgNVBAgTEkdyZWF0ZXIgTWFuY2hlc3RlcjEQMA4G
      A1UEBxMHU2FsZm9yZDEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMTcwNQYDVQQD
      Ey5TZWN0aWdvIFJTQSBEb21haW4gVmFsaWRhdGlvbiBTZWN1cmUgU2VydmVyIENB
      MB4XDTIzMDgwMTAwMDAwMFoXDTI0MDgxNzIzNTk1OVowKDEmMCQGA1UEAwwdKi5j
      cmVkaXRidXJlYXVpbmRvbmVzaWEuY28uaWQwggEiMA0GCSqGSIb3DQEBAQUAA4IB
      DwAwggEKAoIBAQC+92b4YRnF4Lsp4G1W0Ju7eIa97+TW0dIxnHfodXr+4Wt+6r13
      8uUhvK/MrQi6KVOqq3SHctlBWMdcPndr/Mu11eNG865dqC/FyR2vU2qyePyOEaHB
      fAnnOOlDji8kQMLU6imM5NEO3KBZrd9/CN07c3m8plvlttWcgj6SV/boab1fE3ZC
      QIsAwRBHrqE4Knv720yahl7xVXBCLqoK8CiNjB4cdK4oIXgauh6pcGmz9fQIWouj
      Y7TvVl9tLydDUSehXpl7U/bnRIut2sojO5W9djAFqj94yx6MwcZu/Zks3EkrYggq
      KY9b+ZayqNL+UG+QnpZWJwNRF7cel4uJR2s/AgMBAAGjggMeMIIDGjAfBgNVHSME
      GDAWgBSNjF7EVK2K4Xfpm/mbBeG4AY1h4TAdBgNVHQ4EFgQUNS9BBKN9rwU/diKT
      khoYvtfUi0gwDgYDVR0PAQH/BAQDAgWgMAwGA1UdEwEB/wQCMAAwHQYDVR0lBBYw
      FAYIKwYBBQUHAwEGCCsGAQUFBwMCMEkGA1UdIARCMEAwNAYLKwYBBAGyMQECAgcw
      JTAjBggrBgEFBQcCARYXaHR0cHM6Ly9zZWN0aWdvLmNvbS9DUFMwCAYGZ4EMAQIB
      MIGEBggrBgEFBQcBAQR4MHYwTwYIKwYBBQUHMAKGQ2h0dHA6Ly9jcnQuc2VjdGln
      by5jb20vU2VjdGlnb1JTQURvbWFpblZhbGlkYXRpb25TZWN1cmVTZXJ2ZXJDQS5j
      cnQwIwYIKwYBBQUHMAGGF2h0dHA6Ly9vY3NwLnNlY3RpZ28uY29tMEUGA1UdEQQ+
      MDyCHSouY3JlZGl0YnVyZWF1aW5kb25lc2lhLmNvLmlkghtjcmVkaXRidXJlYXVp
    key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+92b4YRnF4Lsp
      4G1W0Ju7eIa97+TW0dIxnHfodXr+4Wt+6r138uUhvK/MrQi6KVOqq3SHctlBWMdc
      Pndr/Mu11eNG865dqC/FyR2vU2qyePyOEaHBfAnnOOlDji8kQMLU6imM5NEO3KBZ
      rd9/CN07c3m8plvlttWcgj6SV/boab1fE3ZCQIsAwRBHrqE4Knv720yahl7xVXBC
      LqoK8CiNjB4cdK4oIXgauh6pcGmz9fQIWoujY7TvVl9tLydDUSehXpl7U/bnRIut
      2sojO5W9djAFqj94yx6MwcZu/Zks3EkrYggqKY9b+ZayqNL+UG+QnpZWJwNRF7ce
      l4uJR2s/AgMBAAECggEBAKVz2o4GKvtLez2MCY93DAaAJVW42+7XOaLsKuOHrbnY
      +naq0N903dq+DR5rKK2KEshC5qJX+i1oysl8AaHZE3IGz3RwujjA+CsH1aVKw52/
      vykj0568ZiQkJc33CZcCWQt5mehNc2fJ9U/dmk8JEgxpPycYh3ReVXLVUXsfpXe0
      bXDLiLlcfXwClYm7s/nvzjAZzIsWFWHt0LWX57sY7HiHQaePpgltn9THQ2tBD2bq
      xlJuifDagFEyK8xrSeWLTvdGgcRhWckJs1I0flOqaD1Gq8DHaUUa69of7+V8tNoe
      mZx+twYsBbVWWMuP78B6Jus6Ltc22STJvzgxNmhkWIkCgYEA7I+4ga03LfeMmq92
      QKZ7DrxDYFuQ/1B7mClrn0R7CzEDzpwmGkVf7ltqMpOV16ipCtEwvuK0ZqcJwfWZ
      GQKFt1rrU0a7RRAnn4iEBSlJkoqYU5z1W+H27iNVKzCeegyRbtg/+VOZPWxFS9KR
      yx4eYagP89OMNNjTz+sdUNnWddUCgYEAzqiM4XiM818Ocf7Pqt363P5GDJYWgTiy
      srEjm/kbq+gATgcZA250eOWkuiadSrSYgBIV6TICfN7h9fsYfbpO5q49T6tegtdm
      OtfQtI40qtZIsgkevZRroaqYpn2VTu5bsGBzJ8n5xWYRJmWnCE6FKux6qV/51zRZ
      U+XjSzYAAsMCgYEAjfCSWaSwNjGRuQLM5m+96JKHrtpiPv9wmVVJERBK7+UiDqdc
      qWi07dUF/IDXaMX3X9ky8WYfrnRNg4a0rO/5gZHZH2eSWBcgXzXPWTVzwqzMR2cn
      RVFpE2w53ydV/49o9+RjRlul19gOIDehaQmSWzA3Gir1toPfW6MMPQXoC10CgYAi
    snis:
      - apisix-dashboard.creditbureauindonesia.co.id
